#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git commit -v --dry-run | grep '@nocommit' >/dev/null 2>&1
then
  echo "Trying to commit non-committable code."
  echo "Remove the @nocommit string and try again."
  exit 1
fi

npx lint-staged
